name: Continuous Integration
on:
  pull_request:
  push:
    branches: [master]
jobs:
  lint-and-test:
    runs-on: github-hosted-small
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: 'true'

      - name: Install dependencies
        run: npm ci

      - name: Install Node
        uses: actions/setup-node@v6

      - name: Run Linter
        run: npm run lint

      - name: Build app
        run: npm run build

  scan:
    needs: lint-and-test
    if: ${{ github.event_name == 'pull_request' && github.event.repository.private == false }}
    uses: circlefin/circle-public-github-workflows/.github/workflows/pr-scan.yaml@v1

  release-sbom:
    needs: lint-and-test
    if: github.event_name == 'push'
    uses: circlefin/circle-public-github-workflows/.github/workflows/attach-release-assets.yaml@v1